### ISSUE TITLE
tokio-runtime-worker panic

### ISSUE THREAD

**Issue by dmitris** [Tuetuopay/catp-ebpf#1]
I'm running `catp-ebpf` and it seems to work all right = prints the process output, but periodically there are these messages:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/dmitris/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45
```

**Comment by Tuetuopay** [comment]
Hi! Sorry for taking so long to take a look in it. This was a mistake on my side for not using matching version of aya-log between userspace and ebpf. Thanks for the report.
